### ISSUE TITLE
Object functions are not recognized

### ISSUE THREAD

**Issue by gpavlov2016** [romainl/ctags-patterns-for-javascript#22]
Example:
```
testobj = {
  func1: () => {
    console.log('test1');
  },
  func2: () => {
    console.log('test2');
  }
};
```
In this case func1 is recognized but func2 is not.
Interesting that if the call inside func1 is removed then both func1 and func2 are recognized:
```
testobj = {
  func1: () => {
  },
  func2: () => {
    console.log('test2');
  }
};

```

**Comment by romainl** [comment]
Here, running `ctags` on a file containing only the first sample or only the second sample produces nothing.

* `testobj` is not tagged because it doesn't have a `var/let/const` keyword, this should be changed.
* `func1()` and `func2()` are not tagged because I don't have a pattern for arrow functions as object methods, this should be changed.

As a matter of fact, there are other places where I should add arrow functions support.

**Comment by romainl** [comment]
This construct is now supported. Thank you.

**Comment by fabriziobertoglio1987** [comment]
with class syntax does not work

```javascript
class Test {
  method = (param) => { 
    console.log('test');
  }
}
```
